STRING_ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 +-*/=><();_!@#$%&?| \t\n"

REGEX_SPEC = [
    ("NUM", "num"),
    ("TEXT", "text"),
    ("BOOL", "bool"),
    ("SHOW", "show"),
    ("TRUE", "true"),
    ("FALSE", "false"),
    ("OP_EQ", "=="),
    ("OP_ASSIGN_OR_EQ", "="),
    ("OP_ADD", "+"),
    ("OP_SUB", "-"),
    ("OP_MULT", "*"),
    ("OP_DIV", "/"),
    ("OP_GT", ">"),
    ("OP_LT", "<"),
    ("LPAREN", "("),
    ("RPAREN", ")"),
    ("SEMICOLON", ";"),
    ("INT_LITERAL", "[0-9]+"),
    ("ID", "letter(letter|digit|_){0,29}"),
    ("STRING", "\"(any_char_except_quote)*\"")
]

TOKEN_OUTPUT_NAME = {
    "NUM":              "NUM",
    "TEXT":             "TEXT",
    "BOOL":             "BOOL",
    "SHOW":             "SHOW",
    "TRUE":             "TRUE",
    "FALSE":            "FALSE",
    "OP_EQ":            "EQ",
    "OP_ASSIGN_OR_EQ":  "EQ",
    "OP_ADD":           "ADD",
    "OP_SUB":           "SUB",
    "OP_MULT":          "MULT",
    "OP_DIV":           "DIV",
    "OP_GT":            "GT",
    "OP_LT":            "LT",
    "LPAREN":           "LPAREN",
    "RPAREN":           "RPAREN",
    "SEMICOLON":        "SEMICOLON",
    "INT_LITERAL":      "NUM",
    "ID":               "VAR",
    "STRING":           "CONST",
}